### ISSUE TITLE
Where are contentypes defined?

### ISSUE THREAD

**Issue by saelfaer** [hvperdrive/pelorus-cms#139]
What defines a contentype? 
suppose i want to make a limited Rich Text Editor 
not allowing everything that's currently in an RTE.

an entry in the fieldTypes collection is a start,
but where else do we need work?

**Comment by saelfaer** [comment]
I meant field types

**Comment by ThomasBormans** [comment]
If I understand your correctly - and I am not saying I do - this is currently not possible. All field types are _hard coded_. Using the Rich Text Editor allows the user to use all the available options.

**Comment by peeterslaurens** [comment]
This is correct, however it would be nice that the rich text-field has some options like “buttons/actions available”.

**Comment by saelfaer** [comment]
Ok, hardcoded for now is fine. however I'd love to discuss a way to make fieldTypes dynamic ...(more dynamic than hardcoding new field types) 

I will close this one and propose a solution which we can debate and discuss before defining a strategy for the future.
